image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build:
  stage: build
  script: gradle clean linuxMainKlibrary
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: push
    paths:
      - build
      - .gradle
