package dev.yoshirulz.ytkt

data class Channel(val id: ChannelID, val title: String, val logoURI: String) {
	@EntryPoint
	val canonicalURI: URI get() = id.canonicalURI

	override fun toString() = "[channel] $title"
}

data class ChannelID internal constructor(val raw: String) {
	val canonicalURI: URI get() = ytCanonicalURI("/channel/$raw")

	/** This channel's "Favorites" playlist */
	@EntryPoint
	val linkedFavoritesPlaylist: PlaylistID get() = PlaylistID(raw.replaceRange(0..1, "FL"), PlaylistID.Companion.PlaylistType.ChannelFavorites)

	/** This channel's "Liked videos" playlist */
	@EntryPoint
	val linkedLikesPlaylist: PlaylistID get() = PlaylistID(raw.replaceRange(0..1, "LL"), PlaylistID.Companion.PlaylistType.ChannelLiked)

	/** Like [linkedUploadsPlaylist], but sorted by popularity instead of upload time */
	@EntryPoint
	val linkedPopularPlaylist: PlaylistID get() = PlaylistID(raw.replaceRange(0..1, "PU"), PlaylistID.Companion.PlaylistType.PopularUploads)

	/** The autogenerated playlist of all the channel's uploads */
	@EntryPoint
	val linkedUploadsPlaylist: PlaylistID get() = PlaylistID(raw.replaceRange(0..1, "UU"), PlaylistID.Companion.PlaylistType.ChannelUploads)

	@RequiresXMLParser
	suspend fun getData(scraper: YTKtScraper): Channel = scraper.getAndParseHTML(canonicalURI).let { channelPageBody ->
		Channel(
			this,
			channelPageBody.querySelector("meta[property=\"og:title\"]")!!.getAttribute("content"),
			channelPageBody.querySelector("meta[property=\"og:image\"]")!!.getAttribute("content")
		)
	}

	override fun toString() = raw

	companion object {
		const val CHANNEL_ID_PATTERN_FRAGMENT = """[\-0-9A-Z_a-z]{22}"""

		/** matches `UC3xnGqlcL3y-GXz5N3wiTJQ` */
		private val CHANNEL_ID_PATTERN = Regex("^UC$CHANNEL_ID_PATTERN_FRAGMENT\$")

		fun parse(raw: String): ChannelID? = if (CHANNEL_ID_PATTERN matches raw) ChannelID(raw) else null

		fun parseFromURI(uri: URI): ChannelID? = uri.encodedPath.let {
			if (YouTubeDomain.ofURI(uri) == YouTubeDomain.MainOrMirror && it.startsWith("/channel/"))
				parse(it.substring(9).substringBefore('/'))
			else null
		}
	}
}
